import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/day_entry.dart';
import '../models/user_profile.dart';

const List<String> _kMonthNames = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];
const List<String> _kWeekdayShort = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

/// Month-er pura statement ke ekta A4 PDF banay - ekta page-er moddheyi
/// (31 din + total row shoho) fit kore, ar page-tao valo moto bhorat
/// thake.
class PdfService {
  Future<void> exportMonth({
    required UserProfile? profile,
    required int year,
    required int month,
    required List<DayEntry> days,
    required RateSettings rates,
    required double totOT,
    required int totNight,
    required int totDuty,
    required int totDayOff,
    required double totalAmount,
    required String currencyCode,
  }) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(28, 40, 28, 34),
        build: (context) => [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _header(profile, year, month),
              pw.SizedBox(height: 12),
              pw.Divider(thickness: 1, color: PdfColors.grey400),
              pw.SizedBox(height: 6),
              _table(days, year, month, totOT, totNight, totDuty, totDayOff),
              pw.SizedBox(height: 8),
              pw.Container(
                width: double.infinity,
                padding: const pw.EdgeInsets.symmetric(vertical: 9, horizontal: 14),
                decoration: pw.BoxDecoration(color: PdfColors.indigo900, borderRadius: pw.BorderRadius.circular(6)),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: pw.CrossAxisAlignment.center,
                  children: [
                    pw.Text('TOTAL AMOUNT (GROSS)',
                        style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 11)),
                    pw.Text('$currencyCode ${totalAmount.toStringAsFixed(2)}',
                        style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 15)),
                  ],
                ),
              ),
              // Footer-ta ekhon aro niche, ar aro halka (subtle) - total
              // box theke boro gap rekhe page-er nicher khali jayga
              // kaje lagano hocche, kintu 1 page-er moddheyi thakche.
              pw.SizedBox(height: 34),
              pw.Divider(thickness: 0.5, color: PdfColors.grey200),
              pw.SizedBox(height: 6),
              pw.Center(
                child: pw.Text('PDF Generated By Progress App',
                    style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey500)),
              ),
              pw.SizedBox(height: 2),
              pw.Center(
                child: pw.Text('Developed by S Matrix Ltd.',
                    style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey500)),
              ),
              pw.SizedBox(height: 2),
              pw.Center(
                child: pw.Text('(C) 2026 S Matrix Ltd. All rights reserved.',
                    style: const pw.TextStyle(fontSize: 7, color: PdfColors.grey400)),
              ),
            ],
          ),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (format) async => doc.save());
  }

  /// App-er home screen header-er sathe hubohu milie banano - title,
  /// subtitle, tarpor Name/ID/Company/Address protyekta nijer line-e.
  /// "MONTH OF ..." badge-ta ekhon Row-er "end" (bottom) e align kora -
  /// mane address block-er niche giye boshe, title-er sathe upore na
  /// theke.
  pw.Widget _header(UserProfile? profile, int year, int month) {
    final name = profile?.name ?? '';
    final id = profile?.employeeId ?? '';
    final company = profile?.company ?? '';
    final address = profile?.address ?? '';

    return pw.Row(
      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
      crossAxisAlignment: pw.CrossAxisAlignment.end,
      children: [
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text('Monthly Duty & Payout Summary',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 2),
              pw.Text('Track Duty, OT & Estimated Earnings',
                  style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
              pw.SizedBox(height: 8),
              if (name.isNotEmpty)
                pw.Text(name, style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11)),
              if (id.isNotEmpty)
                pw.Text('ID: $id', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
              if (company.isNotEmpty)
                pw.Text(company, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
              if (address.isNotEmpty)
                pw.Text(address, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
            ],
          ),
        ),
        pw.SizedBox(width: 12),
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 6),
          decoration: pw.BoxDecoration(
            color: PdfColors.indigo50,
            borderRadius: pw.BorderRadius.circular(6),
            border: pw.Border.all(color: PdfColors.indigo100, width: 0.7),
          ),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('MONTH OF', style: const pw.TextStyle(fontSize: 7.5, color: PdfColors.grey500)),
              pw.SizedBox(height: 2),
              pw.Text('${_kMonthNames[month - 1]} $year',
                  style: pw.TextStyle(fontSize: 12.5, fontWeight: pw.FontWeight.bold, color: PdfColors.indigo900)),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _table(List<DayEntry> days, int year, int month, double totOT, int totNight, int totDuty, int totDayOff) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.5),
      columnWidths: const {
        0: pw.FlexColumnWidth(2.1),
        1: pw.FlexColumnWidth(1.3),
        2: pw.FlexColumnWidth(1.5),
        3: pw.FlexColumnWidth(1.5),
        4: pw.FlexColumnWidth(1.5),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.indigo100),
          children: [
            _cell('DATE', bold: true, fontSize: 8.5),
            _cell('OT(H)', bold: true, center: true, fontSize: 8.5, shiftLeft: true),
            _cell('NIGHT DUTY', bold: true, center: true, fontSize: 8.5),
            _cell('OFF DAY DUTY', bold: true, center: true, fontSize: 8.5),
            _cell('OFF DAY', bold: true, center: true, fontSize: 8.5),
          ],
        ),
        ...List.generate(days.length, (i) {
          final d = i + 1;
          final date = DateTime(year, month, d);
          final wd = date.weekday;
          final dateLabel =
              '${d.toString().padLeft(2, '0')}.${month.toString().padLeft(2, '0')}.$year (${_kWeekdayShort[wd % 7]})';
          final e = days[i];
          return pw.TableRow(children: [
            _cell(dateLabel, fontSize: 8.5),
            _cell(_num(e.ot), center: true, fontSize: 8.5, shiftLeft: true),
            _cell(e.hasNight ? 'Y' : '', center: true, fontSize: 8.5),
            _cell(e.hasDuty ? 'Y' : '', center: true, fontSize: 8.5),
            _cell(e.hasDayoff ? 'Y' : '', center: true, fontSize: 8.5),
          ]);
        }),
        // Totals row - column-er sathe milie protyek column-er total
        // ekhane dekhano hocche.
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.indigo50),
          children: [
            _cell('TOTAL', bold: true, fontSize: 8.5),
            _cell(_num(totOT), bold: true, center: true, fontSize: 8.5, shiftLeft: true),
            _cell('$totNight', bold: true, center: true, fontSize: 8.5),
            _cell('$totDuty', bold: true, center: true, fontSize: 8.5),
            _cell('$totDayOff', bold: true, center: true, fontSize: 8.5),
          ],
        ),
      ],
    );
  }

  String _num(double n) => n == n.roundToDouble() ? n.toInt().toString() : n.toString();

  /// shiftLeft: OT(H) column-ta baki column-er tulonay ektu shongkirno
  /// bole center-align korle visually right-ghenshe mone hoy - tai ei
  /// column-er jonne left-padding kombiye, right-padding baড়িয়ে text-ta
  /// ektu bam-dike sorano hocche, jate column-er majher gap gula shoman
  /// dekhay.
  pw.Widget _cell(String text, {bool bold = false, bool center = false, double fontSize = 8.5, bool shiftLeft = false}) =>
      pw.Padding(
        padding: shiftLeft
            ? const pw.EdgeInsets.only(left: 1, right: 7, top: 3, bottom: 3)
            : const pw.EdgeInsets.symmetric(vertical: 3, horizontal: 4),
        child: pw.Text(
          text,
          textAlign: center ? pw.TextAlign.center : pw.TextAlign.left,
          style: pw.TextStyle(fontSize: fontSize, fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal),
        ),
      );
}
